
import Navbar from "@/components/Navbar";
import "./globals.css";
import Hero from "@/components/Hero";
import { ToastContainer } from "react-toastify";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en "
      className="hydrated"
    >
      <body className="min-h-full flex flex-col">
        
        <Navbar/>
         <ToastContainer />
        {children}



      </body>
    </html>
  );
}
